from __future__ import annotations

from mcp.server import MCPServer

mcp = MCPServer("Raspberry Pi")

from .audio import (
    play_audio,
    stop_audio,
    notify_audio,
    list_notification_audios,
    play_alarm,
    list_alarm_audios,
    mute,
    unmute,
    get_volume,
    set_volume,
    mute_mic,
    unmute_mic,
    set_mic_volume,
    get_mic_mute_state_resource,
    get_mic_volume,
)
from .display import (
    list_cube_gifs,
    get_cube_current_gif,
    get_cube_free_space,
    set_cube_gif,
    get_cube_brightness,
    set_cube_brightness,
    turn_cube_display_off,
    turn_cube_display_on,
    upload_cube_image,
    save_image_in_gallery,
    show_gallery_image,
    show_gallery_gif,
    show_temporary_gif,
    get_random_image_status,
    list_gallery_images,
    list_gallery_gifs,
    start_random_images,
    stop_random_images,
    get_random_gif_status,
    start_random_gifs,
    stop_random_gifs,
)
from .image import take_photo
from .video import record_video

__all__ = [
    "mcp",
    "play_audio",
    "stop_audio",
    "notify_audio",
    "list_notification_audios",
    "play_alarm",
    "list_alarm_audios",
    "mute",
    "unmute",
    "get_volume",
    "set_volume",
    "mute_mic",
    "unmute_mic",
    "set_mic_volume",
    "get_mic_mute_state_resource",
    "get_mic_volume",
    "list_cube_gifs",
    "get_cube_current_gif",
    "get_cube_free_space",
    "set_cube_gif",
    "get_cube_brightness",
    "set_cube_brightness",
    "turn_cube_display_off",
    "turn_cube_display_on",
    "upload_cube_image",
    "save_image_in_gallery",
    "show_gallery_image",
    "show_gallery_gif",
    "show_temporary_gif",
    "get_random_image_status",
    "list_gallery_images",
    "list_gallery_gifs",
    "start_random_images",
    "stop_random_images",
    "get_random_gif_status",
    "start_random_gifs",
    "stop_random_gifs",
    "take_photo",
    "record_video",
]
